language: python
matrix:
  include:
  - python: '3.7'
  - python: '3.8'
    after_script:
    - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    packages:
    - ldap-utils
    - slapd
install:
- pip install coverage
- python setup.py install
script:
- python runtests.py
deploy:
  provider: pypi
  user: __token__
  on:
    python: '3.8'
  password:
    secure: AI7llpFEUMMOn4hKDLk6x6X3O8IcX9EOKPW9HIi25fjfLdx1v9trampYaPfFixD5mHkxRJBvynNFxLeTtf5WrpnvkWxe17K+kqNfHbraM33T85tDYN6BQpmQeu5wyPupPaEE+30vc5ifXodBo6fU1r5++UmVrLmQtxGsEiJ0f8G/JSssBlmiIkVMcWpJZXBcGZt5x8hl7GcL7GWrDLkVRkUQXkBGgsWmX4lR/sX8yo3H2V+JL4Qy/8jRhAZqPxtgdrsDO7P62hOKrpsp7KVRlsMUuWONjnixtKu4RWZQFsTQjBosyo9C+xvFWchhcGbgByOGa46jt6PKUVm3/peJFMR8l4h/jVfB0TbKXCQr+i4gPCxIEYxgrv54p13eUF2qHOv+HpQJI+634hHAt3vxvaaaNcvzVFFeVpmvGdNlIpI+8YSCqUgO5MX36kNSVEuCePK4ZraVs3MvEdNBwkOv51wAGdIgh0ZCd5QvdLJhBJykZGpLyaauWUZucqnDa/9ch0oeLtbuCCl/jFWYfPf8Ai2twccD/3qMG7ZrRnkewbYImBNag5JrlKYNb1kXRvdr9qAIkZGKboNH9/8FfrPTq7TbVvkCj773gG7czi3kZ/QF5dMBQotYyuG1ukTdOmTt8I4JDyYJBtRqnKanZaUS61Ld1huZq2JbOmuFa8ItXyU=
